"""Apply the five approved audit-status updates; mathematical body stays exact."""
from pathlib import Path
import json, hashlib, difflib, re
ROOT=Path(__file__).resolve().parent
BASE=ROOT.parent/'v1.22_editorial_candidate_r2'
replacements={
'en':[
('**Status:**', '**Status:** the v1.22-r2 external review concluded PASS_WITH_OBSERVATIONS on October 1, 2026. It accepted the expanded C.3 argument and all seven derivations in A.2; no finding of severity MINOR or higher remained open. The Lean source cut remains `piv-v12-fb459343d234`, with formal PASS inherited from the verified external build. This r3 package updates audit-status information; its documentary delta awaits verification. No new Lean build is claimed. This candidate has not been published or assigned its own DOI.'),
('**Audit status of this editorial candidate.**','**Audit status of this editorial candidate.** The internal run `run_20260929_v1.2_fb459343d234_r1` recorded PASS for its declared scope. The external build in `run_v1.2_r1` compiled 607 main modules, all 19 targets and the 50-module annex; the 607 main objects were byte-identical to the author’s objects. That review and `run_v1.21_r1` were INCONCLUSIVE overall because exposition remained incomplete. The expanded C.3 comparison was accepted in `run_v1.22_r1`, completing the seven A.2 derivations. The consolidated `run_v1.22_r2` returned PASS_WITH_OBSERVATIONS and closed the remaining Spanish corrections. Its observations and scope limitations are retained in the report. Revalidations used unchanged sources and existing build evidence, without recompilation. This r3 documentary update is submitted separately; it does not claim a new formal build or a verdict for its own changes.'),
('The single audit command described in §7','The single audit command described in §7 executes all 19 targets, including the root, the individual audit targets and the export check. Lean and dependency revisions are recorded in lean-toolchain and lake-manifest.json. Compilation, public export, axiom inspection and semantic correspondence are distinct checks. The source freeze is unchanged. The external build passed in v1.2 and its evidence was revalidated in subsequent revisions without recompilation. The consolidated v1.22-r2 report records the accepted C.3 expansion and distinguishes individual semantic comparisons from statements covered by the proof-component ledger and compiled declarations.'),
('**Scope of the written proof.**','**Scope of the written proof.** The table below records derivations that received particular scrutiny. Revision 1.21 expanded the bilateral fibre cleaning in C.2, the normalization counts and joint elimination in E.1, and the numerical schedule in C.3. Revision 1.22 then supplied the regularity recurrence and the final tower comparison. The consolidated v1.22-r2 report classifies all seven rows as ACCEPTABLE_SUMMARY. It retains the stated expository limit concerning the cited second-moment estimates in C.2. A successful build checks formal derivations, not completeness of exposition; the written-proof assessment remains distinct from compilation and from human peer review.'),
('Appendix E.4 derives the retained terminal accounts','Appendix E.4 derives the retained terminal accounts used in §6.6, F.3 proves clique recovery, and F.5 explains the three-case assembly of the adapted pinned-sample bound. Their recorded checks are consolidated in the v1.22-r2 report, with the scope and limitations stated there. These checks compare the written accounts with the frozen formal development; they do not turn local compilation into a substitute for mathematical review.')],
'es':[
('**Estado:**','**Estado:** la revisión externa v1.22-r2 concluyó PASS_WITH_OBSERVATIONS el 1 de octubre de 2026. Aceptó la ampliación de C.3 y las siete derivaciones de A.2; no quedaron hallazgos abiertos de severidad MINOR o superior. El corte Lean sigue siendo `piv-v12-fb459343d234`, con PASS formal heredado del build externo verificado. Este paquete r3 actualiza la información de auditoría; su cambio documental espera verificación. No se afirma un nuevo build Lean. Esta candidata no se ha publicado ni tiene DOI propio asignado.'),
('**Estado de auditoría de esta candidata editorial.**','**Estado de auditoría de esta candidata editorial.** La ejecución interna `run_20260929_v1.2_fb459343d234_r1` registró PASS para su alcance declarado. El build externo de `run_v1.2_r1` compiló 607 módulos principales, los 19 objetivos y el anexo de 50 módulos; los 607 objetos principales fueron idénticos byte a byte a los del autor. Esa revisión y `run_v1.21_r1` dieron INCONCLUSIVE global porque faltaba completar la exposición. La comparación ampliada de C.3 fue aceptada en `run_v1.22_r1`, completando las siete derivaciones de A.2. El informe consolidado `run_v1.22_r2` dio PASS_WITH_OBSERVATIONS y cerró las correcciones españolas restantes. Sus observaciones y límites de alcance se conservan en el informe. Las revalidaciones utilizaron las fuentes sin cambios y la evidencia del build existente, sin recompilar. Esta actualización documental r3 se presenta por separado; no afirma un nuevo build formal ni un veredicto sobre sus propios cambios.'),
('El comando único de auditoría descrito en §7','El comando único de auditoría descrito en §7 ejecuta los 19 objetivos, incluidos la raíz, los objetivos individuales de auditoría y el control de exportación. Las revisiones de Lean y sus dependencias están registradas en lean-toolchain y lake-manifest.json. Compilación, exportación pública, inspección de axiomas y correspondencia semántica son controles distintos. El congelado de fuentes no cambia. El build externo pasó en v1.2 y su evidencia se revalidó en las revisiones posteriores sin recompilar. El informe consolidado v1.22-r2 registra la aceptación de la ampliación de C.3 y distingue las comparaciones semánticas individuales de los enunciados cubiertos por el registro de componentes de prueba y las declaraciones compiladas.'),
('**Alcance de la prueba escrita.**','**Alcance de la prueba escrita.** La tabla siguiente registra las derivaciones que recibieron especial atención. La versión 1.21 amplió la limpieza bilateral de fibras de C.2, los conteos de normalización y la eliminación conjunta de E.1, y la programación numérica de C.3. La versión 1.22 añadió la recurrencia de regularidad y la comparación final con la torre. El informe consolidado v1.22-r2 clasifica las siete filas como ACCEPTABLE_SUMMARY. Conserva el límite expositivo declarado sobre las estimaciones de segundo momento citadas en C.2. Un build satisfactorio verifica derivaciones formales, no la integridad de su exposición; la evaluación de la prueba escrita sigue siendo distinta de la compilación y de la revisión humana por pares.'),
('El Apéndice E.4','El Apéndice E.4 desarrolla las cuentas terminales conservadas que se usan en §6.6, F.3 demuestra la recuperación de la clique y F.5 explica el ensamblaje de tres casos de la cota adaptada con muestra fijada. Sus comprobaciones registradas se consolidan en el informe v1.22-r2, con el alcance y los límites allí declarados. Esas comprobaciones contrastan las cuentas escritas con el desarrollo formal congelado; no convierten la compilación local en un sustituto de la revisión matemática.')]
}
report={}
for lang, changes in replacements.items():
    p=ROOT/f'PAPER_IV_preprint_v1.22_{lang}.md'
    original=(BASE/p.name).read_text(encoding='utf-8'); lines=original.splitlines()
    changed=[]
    for prefix,new in changes:
        if lang=='es' and prefix=='**Alcance de la prueba escrita.**':
            prefix='**Alcance de la demostración escrita.**'
        hits=[i for i,s in enumerate(lines) if s.startswith(prefix)]
        assert len(hits)==1,(lang,prefix,hits)
        i=hits[0]; changed.append({'line':i+1,'before':lines[i],'after':new}); lines[i]=new
    output='\n'.join(lines)+'\n'
    for pattern in (r'\\\[.*?\\\]',r'\\\(.*?\\\)',r'```.*?```',r'\\tag\{[^}]+\}'):
        assert re.findall(pattern,original,re.S)==re.findall(pattern,output,re.S)
    assert original.split('## Refer')[1]==output.split('## Refer')[1]
    p.write_text(output,encoding='utf-8')
    (ROOT/f'CHANGES_{lang}.diff').write_text(''.join(difflib.unified_diff(original.splitlines(True),output.splitlines(True),fromfile='r2/'+p.name,tofile='r3/'+p.name)),encoding='utf-8')
    report[lang]={'changed_paragraphs':changed,'baseline_sha256':hashlib.sha256((BASE/p.name).read_bytes()).hexdigest(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'math_code_tags_references_identical':True}
(ROOT/'STATUS_DELTA.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print({k:len(v['changed_paragraphs']) for k,v in report.items()})
