/-
# Nibble — McDiarmid bridge (hand assembly), Layer M

Standalone, Mathlib-only. Building McDiarmid's bounded-differences inequality by hand, in layers,
on top of `Nibble.CondHoeffding` (M3) and Mathlib's Azuma–Hoeffding.

This file is under active construction. Current layer:
* **M1 — exposure filtration** `exposureσ k`: the σ-algebra generated by the first `k` coordinates
  of a finite product space, packaged as a `MeasureTheory.Filtration`.

Must stay sorry-free and axiom-clean `[propext, Classical.choice, Quot.sound]`.
-/
import Nibble.CondHoeffding
import Nibble.Prelude

open MeasureTheory ProbabilityTheory Finset

namespace Nibble

variable {n : ℕ} {α : Fin n → Type*} [∀ i, MeasurableSpace (α i)]

/-- The σ-algebra on the product space `∀ i, α i` generated by the first `k` coordinates. -/
def exposureσ (k : ℕ) : MeasurableSpace (∀ i, α i) :=
  ⨆ (i : Fin n) (_ : (i : ℕ) < k), MeasurableSpace.comap (fun ω => ω i) inferInstance

theorem exposureσ_mono : Monotone (exposureσ (α := α)) := by
  intro k k' hk
  refine iSup₂_le fun i hi => ?_
  exact le_iSup₂_of_le i (lt_of_lt_of_le hi hk) le_rfl

theorem exposureσ_le (k : ℕ) : exposureσ (α := α) k ≤ MeasurableSpace.pi := by
  refine iSup₂_le fun i _ => ?_
  exact (measurable_iff_comap_le).mp (measurable_pi_apply i)

/-- **M1 — the exposure filtration.** The first-`k`-coordinates σ-algebras form a filtration on the
finite product space (indexed by `ℕ`, w.r.t. the product σ-algebra `MeasurableSpace.pi`). -/
def exposureFiltration : @Filtration (∀ i, α i) ℕ _ MeasurableSpace.pi where
  seq := exposureσ
  mono' := exposureσ_mono
  le' := exposureσ_le

/-- **Doob martingale** of `f` for the exposure filtration: `g k = μ[f | ℱ k]`. -/
noncomputable def doob (μ : Measure (∀ i, α i)) (f : (∀ i, α i) → ℝ) (k : ℕ) :
    (∀ i, α i) → ℝ :=
  (μ[f | exposureσ k] : _)

/-- **M2(a) — the Doob martingale is adapted** to the exposure filtration. -/
theorem doob_stronglyMeasurable (μ : Measure (∀ i, α i)) (f : (∀ i, α i) → ℝ) (k : ℕ) :
    StronglyMeasurable[exposureσ k] (doob μ f k) :=
  stronglyMeasurable_condExp

/-- Exposing zero coordinates yields the trivial σ-algebra. -/
theorem exposureσ_zero : exposureσ (α := α) 0 = ⊥ :=
  le_antisymm (iSup₂_le fun _ hi => absurd hi (Nat.not_lt_zero _)) bot_le

/-- **M2(b) — endpoint `g₀ = E[f]`.** The Doob martingale at time `0` is the constant mean. -/
theorem doob_zero (μ : Measure (∀ i, α i)) [IsProbabilityMeasure μ]
    (f : (∀ i, α i) → ℝ) :
    doob μ f 0 = fun _ => ∫ x, f x ∂μ := by
  show (μ[f | exposureσ 0] : _) = _
  rw [exposureσ_zero, condExp_bot]

/-- Exposing all `n` coordinates yields the full product σ-algebra. -/
theorem exposureσ_full : exposureσ (α := α) n = MeasurableSpace.pi := by
  refine le_antisymm (exposureσ_le n) (iSup_le fun i => ?_)
  exact le_iSup₂_of_le i i.isLt le_rfl

/-- **M2(c) — endpoint `gₙ = f`.** After exposing all coordinates the Doob martingale recovers `f`
(a.e.), for measurable integrable `f`. -/
theorem doob_full (μ : Measure (∀ i, α i)) [IsProbabilityMeasure μ]
    {f : (∀ i, α i) → ℝ} (hf : StronglyMeasurable f) (hfi : Integrable f μ) :
    doob μ f n = f := by
  show (μ[f | exposureσ n] : _) = f
  rw [exposureσ_full]
  exact condExp_of_stronglyMeasurable le_rfl hf hfi

end Nibble
