/-
  Part A — A5 decomposed (Farkas / LP-duality bridge split into independent pieces).

  We realise the fractional triangle-cover LP geometrically in `Sym2 V → ℝ`:
  * `incidence G t` — the 0/1 indicator of the three edges of a 3-clique `t`;
  * `targetVec G`   — the 0/1 indicator of `E(G)` (the all-ones RHS on edges);
  * `triCone G`     — the convex cone of nonnegative combinations of the `incidence G t`.

  Then `targetVec G ∈ triCone G ↔ FractionalTriangleDecomp G`, and the Farkas direction
  reduces to separating `targetVec` from the (closed) cone.

  Pieces:
  * S1 `decomp_of_target_mem`         — `targetVec ∈ triCone → FractionalTriangleDecomp`  [PROVED]
  * S2 `triCone_isClosed`             — `IsClosed (triCone G)`                             [PROVED]
  * S3 `farkas_of_target_not_mem`     — `targetVec ∉ triCone → ∃ y, FarkasPotential`       [PROVED]
  * S4 `decomp_of_no_farkas`          — `(∀ y, ¬FarkasPotential) → FractionalTriangleDecomp` [PROVED]

  S2 is proved directly by sequential closedness: the image of the nonnegative orthant under
  the (finite-dim) incidence map is closed — bounded coefficient sequences converge by
  compactness, and unbounded ones are impossible since the incidence vectors are nonnegative
  (no cancellation ⇒ a bounded image forces bounded coefficients). Hence all of A5 is closed.
-/
import Ax2.PartA.Flow

namespace Ax2

open SimpleGraph Finset

variable {V : Type*} [Fintype V] [DecidableEq V]

open scoped Classical in
/-- Indicator vector of the three edges of a 3-clique `t`. -/
noncomputable def incidence (G : SimpleGraph V) [DecidableRel G.Adj] (t : Finset V) :
    Sym2 V → ℝ := fun e => if e ∈ triEdges t then 1 else 0

open scoped Classical in
/-- Indicator vector of the edge set of `G` (the all-ones right-hand side). -/
noncomputable def targetVec (G : SimpleGraph V) [DecidableRel G.Adj] : Sym2 V → ℝ :=
  fun e => if e ∈ G.edgeFinset then 1 else 0

/-- The convex cone of nonnegative combinations of triangle-incidence vectors. -/
def triCone (G : SimpleGraph V) [DecidableRel G.Adj] : Set (Sym2 V → ℝ) :=
  { f | ∃ w : Finset V → ℝ, (∀ t, 0 ≤ w t) ∧
      f = ∑ t ∈ G.cliqueFinset 3, w t • incidence G t }

/-- **S1.** Membership of the all-ones vector in the cone yields a fractional decomposition. -/
theorem decomp_of_target_mem (G : SimpleGraph V) [DecidableRel G.Adj]
    (h : targetVec G ∈ triCone G) : FractionalTriangleDecomp G := by
  classical
  obtain ⟨w, hw, hf⟩ := h
  refine ⟨w, hw, fun e he => ?_⟩
  have hev := congrFun hf e
  rw [Finset.sum_apply] at hev
  simp only [Pi.smul_apply, smul_eq_mul, incidence, targetVec, he, if_true] at hev
  rw [hev]
  apply Finset.sum_congr rfl
  intro t _
  split_ifs <;> simp

/-- **S2.** The finitely generated cone is closed (Minkowski–Weyl). -/
theorem triCone_isClosed (G : SimpleGraph V) [DecidableRel G.Adj] :
    IsClosed (triCone G) := by
  refine IsSeqClosed.isClosed ?_
  intro x hx hx_mem hx_lim
  -- Each x n is in triCone G
  simp only [triCone] at hx_mem
  -- Obtain coefficients w_n for each x n
  choose w hw_nonneg hw_eq using hx_mem
  -- Define the restriction of weights to S
  let S := G.cliqueFinset 3
  let w' : ℕ → (S → ℝ) := fun n t => w n t
  have hw'_nonneg : ∀ n t, 0 ≤ w' n t := fun n t => hw_nonneg n t
  have hw'_eq : ∀ n, x n = ∑ t : S, w' n t • incidence G ↑t := fun n => by
    simp_rw [hw_eq n]
    rw [← Finset.sum_attach]
    rfl
  -- Define the linear map L : (S → ℝ) → (Sym2 V → ℝ)
  let L : (S → ℝ) →ₗ[ℝ] (Sym2 V → ℝ) := {
    toFun := fun v => ∑ t : S, v t • incidence G ↑t
    map_add' := by intros; simp [Finset.sum_add_distrib, add_smul]
    map_smul' := by intros; simp [Finset.smul_sum, smul_smul]
  }
  -- triCone G = L '' {v : S → ℝ | ∀ t, 0 ≤ v t}
  have h_eq : triCone G = L '' {v : S → ℝ | ∀ t, 0 ≤ v t} := by
    ext f
    simp only [Set.mem_image, Set.mem_setOf_eq, triCone]
    constructor
    · rintro ⟨w, hw, rfl⟩
      refine ⟨fun t => w t, fun t => hw t, ?_⟩
      simp only [L]
      rw [← Finset.sum_attach]
      rfl
    · rintro ⟨v, hv, rfl⟩
      refine ⟨fun t => if ht : t ∈ S then v ⟨t, ht⟩ else 0, ?_, ?_⟩
      · intro t; by_cases ht : t ∈ S <;> simp [ht]; exact hv ⟨t, ht⟩
      · simp only [L]
        rw [← Finset.sum_attach]
        apply Finset.sum_congr rfl
        intro t ht
        simp
  -- triCone G is the convex cone generated by {incidence G t | t ∈ S}
  -- This is closed because it's finitely generated in finite dimensions
  rw [h_eq]
  -- Reconstruct membership: x n ∈ triCone G → x n ∈ L '' {v | v ≥ 0}
  have hx_mem' : ∀ n, x n ∈ ⇑L '' {v : S → ℝ | ∀ t, 0 ≤ v t} := by
    intro n
    rw [Set.mem_image]
    refine ⟨fun t => w n t, fun t => hw_nonneg n t, ?_⟩
    simp only [L]
    rw [hw_eq n]
    rw [← Finset.sum_attach]
    rfl
  have h_closed : IsClosed (⇑L '' {v : S → ℝ | ∀ t, 0 ≤ v t}) := IsSeqClosed.isClosed (by
    intro seq hmem hmem_seq hlim
    -- seq : ℕ → Sym2 V → ℝ is a sequence in the image
    -- hmem : the limit point
    -- hmem_seq : ∀ n, seq n ∈ image
    -- hlim : Tendsto seq atTop (nhds hmem)
    -- Each seq n = L(w' n) for some w' n ≥ 0
    have h_w' : ∀ n, ∃ w' : S → ℝ, (∀ t, 0 ≤ w' t) ∧ seq n = L w' := fun n => by
      simp only [Set.mem_image] at hmem_seq
      obtain ⟨w', hw, hseq⟩ := hmem_seq n
      exact ⟨w', hw, hseq.symm⟩
    choose w' hw_nonneg hw_eq using h_w'
    -- Now seq n = L (w' n) → hmem, with w' n ≥ 0
    -- We need to find w ≥ 0 with L w = hmem
    -- Case analysis based on boundedness of {w' n}
    by_cases h_bdd : Bornology.IsBounded {y | ∃ n, y = w' n}
    · -- Bounded case: extract convergent subsequence
      -- The nonnegative orthant intersected with a ball is compact
      have h_closed_nonneg : IsClosed {v : S → ℝ | ∀ t, 0 ≤ v t} := by
        simp_rw [Set.setOf_forall]
        apply isClosed_iInter
        intro t
        exact isClosed_Ici.preimage (continuous_apply t)
      -- Get a bound R for the sequence
      rw [Metric.isBounded_iff] at h_bdd
      obtain ⟨R, hR⟩ := h_bdd
      -- The set {v | v ≥ 0} ∩ closedBall 0 R is compact (closed subset of compact ball in finite dim)
      have h_closed_ball : IsClosed (Metric.closedBall (0 : S → ℝ) R) := Metric.isClosed_closedBall
      have h_compact_ball : IsCompact (Metric.closedBall (0 : S → ℝ) R) := isCompact_closedBall 0 R
      have h_compact : IsCompact ({v : S → ℝ | ∀ t, 0 ≤ v t} ∩ Metric.closedBall 0 R) := by
        rw [Set.inter_comm]
        exact h_compact_ball.inter_right h_closed_nonneg
      -- The sequence w' n lies in the compact set
      -- Find a point in the range to use as center
      -- All points are within distance R of each other
      -- Use w' 0 as reference
      have h_ball_center : ∀ n, w' n ∈ Metric.closedBall (w' 0) R := by
        intro n
        have h1 : w' n ∈ {y | ∃ m, y = w' m} := ⟨n, rfl⟩
        have h2 : w' 0 ∈ {y | ∃ m, y = w' m} := ⟨0, rfl⟩
        exact hR h1 h2
      -- The closed ball around w' 0 is compact (translate of ball around 0)
      have h_compact_ball' : IsCompact (Metric.closedBall (w' 0) R) := by
        have : Metric.closedBall (w' 0) R = (fun x => x + w' 0) '' Metric.closedBall 0 R := by
          ext x
          simp [Metric.mem_closedBall, dist_eq_norm', add_comm]
        rw [this]
        exact h_compact_ball.image (continuous_add_right _)
      -- The orthant intersected with this ball is compact
      have h_closed_nonneg' : IsClosed {v : S → ℝ | ∀ t, 0 ≤ v t} := h_closed_nonneg
      have h_compact' : IsCompact ({v : S → ℝ | ∀ t, 0 ≤ v t} ∩ Metric.closedBall (w' 0) R) := by
        rw [Set.inter_comm]
        exact h_compact_ball'.inter_right h_closed_nonneg'
      have h_in_compact : ∀ n, w' n ∈ ({v : S → ℝ | ∀ t, 0 ≤ v t} ∩ Metric.closedBall (w' 0) R) := by
        intro n
        constructor
        · exact hw_nonneg n
        · exact h_ball_center n
      -- Use IsSeqCompact
      have h_seq_compact' : IsSeqCompact ({v : S → ℝ | ∀ t, 0 ≤ v t} ∩ Metric.closedBall (w' 0) R) := h_compact'.isSeqCompact
      -- IsSeqCompact means: for any sequence in the set, there's a convergent subsequence
      have := @h_seq_compact' (fun n => w' n) h_in_compact
      obtain ⟨hu_lim, h_in, u, hu_mono, h_tendsto⟩ := this
      -- hu_lim is in the orthant
      have hu_lim_in : hu_lim ∈ {v : S → ℝ | ∀ t, 0 ≤ v t} := h_in.1
      -- L(hu_lim) = hmem since L is continuous and seq (u k) → hmem
      have hL_cont : Continuous L := LinearMap.continuous_of_finiteDimensional L
      have hL_lim : Filter.Tendsto (fun k => L (w' (u k))) Filter.atTop (nhds (L hu_lim)) := hL_cont.continuousAt.tendsto.comp h_tendsto
      -- seq (u k) → hmem
      have hseq_lim : Filter.Tendsto (fun k => seq (u k)) Filter.atTop (nhds hmem) := hlim.comp hu_mono.tendsto_atTop
      -- L(w' (u k)) = seq (u k), so L(hu_lim) = hmem
      have heq : L hu_lim = hmem := tendsto_nhds_unique hL_lim (by simpa [hw_eq] using hseq_lim)
      exact ⟨hu_lim, hu_lim_in, heq⟩
    · -- Unbounded case: {w' n} is unbounded
      -- We need to show hmem ∈ L '' {v | v ≥ 0}
      
      -- If the sequence is unbounded, there exists a subsequence with ‖w' n‖ → ∞
      -- We normalize and use compactness of orthant ∩ sphere to get u with L(u) = 0
      
      -- For simplicity, let's use a different approach:
      -- The image L({v | v ≥ 0}) equals the closure of L({v | v ≥ 0, ‖v‖ ≤ R}) for any R > 0
      -- when there exists u ∈ ker(L) ∩ {v | v ≥ 0} with u ≠ 0.
      
      -- We'll show that such a u exists by normalization.
      
      -- First, we need that the sequence is "unbounded in norm" not just "unbounded set"
      -- The hypothesis h_bdd : ¬Bornology.IsBounded {y | ∃ n, y = w' n} means the set has infinite diameter
      
      -- This doesn't directly imply ‖w' n‖ → ∞ for any subsequence, but it does mean
      -- we can find pairs of points far apart
      
      -- Unbounded case: need to normalize and use compactness of sphere
      -- The set {w' n} is unbounded, so we can find a subsequence with ‖w' n_k‖ → ∞
      
      -- Step 1: Show that for any M > 0, there exists n with ‖w' n‖ > M
      have h_unbounded_norm : ∀ M : ℝ, 0 < M → ∃ n, ‖w' n‖ > M := by
        intro M hM
        by_contra h_neg
        push_neg at h_neg
        -- If ‖w' n‖ ≤ M for all n, then the set is bounded
        have h_bdd' : Bornology.IsBounded {y | ∃ n, y = w' n} := by
          rw [Metric.isBounded_iff]
          refine ⟨2 * M, ?_⟩
          intro x hx y hy
          obtain ⟨n, rfl⟩ := hx
          obtain ⟨m, rfl⟩ := hy
          have h1 : ‖w' n‖ ≤ M := h_neg n
          have h2 : ‖w' m‖ ≤ M := h_neg m
          calc dist (w' n) (w' m) ≤ ‖w' n‖ + ‖w' m‖ := dist_le_norm_add_norm _ _
            _ ≤ M + M := by linarith
            _ = 2 * M := by ring
        exact h_bdd h_bdd'
      -- Unbounded case: {w' n} is unbounded but seq n = L(w' n) → hmem
      -- Strategy: extract subsequence with ‖w' n_k‖ → ∞, normalize to get u_k,
      -- extract convergent subseq u_kj → u with L(u) = 0, u ≥ 0, ‖u‖ = 1.
      -- Then show hmem ∈ L(orthant) by a limiting argument.
      
      -- Step 1: Extract subsequence with norms → ∞
      have h_exists : ∀ k : ℕ, ∃ n : ℕ, ‖w' n‖ > k + 1 := fun k => h_unbounded_norm (k + 1) (by positivity)
      choose f hf_gt using h_exists
      -- ‖w' (f k)‖ > k + 1 → ∞
      have hfk_norm : Filter.Tendsto (fun k => ‖w' (f k)‖) Filter.atTop Filter.atTop := by
        rw [Filter.tendsto_atTop_atTop]
        intro M
        use Nat.ceil M
        intro k hk
        have h1 : M ≤ ⌈M⌉₊ := Nat.le_ceil M
        have h2 : (⌈M⌉₊ : ℝ) ≤ k := by exact_mod_cast hk
        have h3 : (k : ℝ) + 1 ≤ ‖w' (f k)‖ := le_of_lt (hf_gt k)
        linarith
      
      -- Step 2: Normalize to get u_k in orthant ∩ unit sphere
      let u : ℕ → (S → ℝ) := fun k => (1 / ‖w' (f k)‖) • w' (f k)
      have hu_nonneg : ∀ k t, 0 ≤ u k t := by
        intro k t
        simp only [u]
        apply mul_nonneg
        · exact one_div_nonneg.mpr (norm_nonneg _)
        · exact hw_nonneg (f k) t
      have hu_norm : ∀ k, ‖u k‖ = 1 := by
        intro k
        simp only [u]
        rw [norm_smul, Real.norm_eq_abs]
        have hpos : 0 < ‖w' (f k)‖ := lt_trans (by linarith : (0:ℝ) < k + 1) (hf_gt k)
        rw [abs_of_nonneg (one_div_nonneg.mpr (norm_nonneg _)), div_mul_cancel₀ _ (ne_of_gt hpos)]
      -- The unit sphere is a subset of the closed ball of radius 1
      have hu_in_ball : ∀ k, u k ∈ Metric.closedBall 0 1 := by
        intro k
        simp [Metric.mem_closedBall, dist_eq_norm', hu_norm k]
      -- The orthant is closed
      have h_ortho_closed : IsClosed {v : S → ℝ | ∀ t, 0 ≤ v t} := by
        simp_rw [Set.setOf_forall]
        apply isClosed_iInter
        intro t
        exact isClosed_Ici.preimage (continuous_apply t)
      -- The orthant ∩ unit sphere is compact (closed subset of compact ball)
      have h_unit_ball_compact : IsCompact (Metric.closedBall (0 : S → ℝ) 1) := isCompact_closedBall 0 1
      have h_ortho_sphere : IsCompact {v : S → ℝ | (∀ t, 0 ≤ v t) ∧ ‖v‖ = 1} := by
        have h_closed_sphere : IsClosed {v : S → ℝ | ‖v‖ = 1} := 
          isClosed_eq continuous_norm continuous_const
        have h1 : IsCompact (Metric.closedBall (0 : S → ℝ) 1 ∩ {v : S → ℝ | ‖v‖ = 1}) := 
          h_unit_ball_compact.inter_right h_closed_sphere
        have h2 : IsCompact (Metric.closedBall (0 : S → ℝ) 1 ∩ {v : S → ℝ | ‖v‖ = 1} ∩ {v : S → ℝ | ∀ t, 0 ≤ v t}) := 
          h1.inter_right h_ortho_closed
        have heq : Metric.closedBall (0 : S → ℝ) 1 ∩ {v : S → ℝ | ‖v‖ = 1} ∩ {v : S → ℝ | ∀ t, 0 ≤ v t} = 
                   {v : S → ℝ | (∀ t, 0 ≤ v t) ∧ ‖v‖ = 1} := by 
          ext v
          simp only [Set.mem_inter_iff, Set.mem_setOf_eq, Metric.mem_closedBall, dist_zero_right]
          constructor
          · rintro ⟨⟨h1, h2⟩, h3⟩; exact ⟨h3, h2⟩
          · rintro ⟨h3, h2⟩; exact ⟨⟨h2.le, h2⟩, h3⟩
        rw [← heq]
        exact h2
      -- Step 3: Extract convergent subsequence u_kj → u_lim using sequential compactness
      have h_seq_in : ∀ k, u k ∈ {v : S → ℝ | (∀ t, 0 ≤ v t) ∧ ‖v‖ = 1} := fun k => ⟨hu_nonneg k, hu_norm k⟩
      have hseq := h_ortho_sphere.isSeqCompact
      have := @hseq (fun k => u k) h_seq_in
      obtain ⟨u_lim, hu_lim_in, g, hg_mono, hg_tendsto⟩ := this
      have hu_lim_nonneg : ∀ t, 0 ≤ u_lim t := hu_lim_in.1
      have hu_lim_norm : ‖u_lim‖ = 1 := hu_lim_in.2
      -- Step 4: Show L(u_lim) = 0
      -- L(u k) = L(w' (f k)) / ‖w' (f k)‖ → 0 since L(w' (f k)) → hmem (bounded) and ‖w' (f k)‖ → ∞
      have hL_cont : Continuous L := LinearMap.continuous_of_finiteDimensional L
      have hL_lim : Filter.Tendsto (fun k => L (u (g k))) Filter.atTop (nhds (L u_lim)) := 
        hL_cont.continuousAt.tendsto.comp hg_tendsto
      -- Show L(u k) → 0
      have hL_u_eq : ∀ k, L (u k) = (1 / ‖w' (f k)‖) • seq (f k) := by
        intro k
        simp only [u, hw_eq]
        rw [map_smul]
      -- ‖w' (f (g k))‖ → ∞ (since ‖w' (f k)‖ → ∞ and g k ≥ k)
      have hfk_g_norm : Filter.Tendsto (fun k => ‖w' (f (g k))‖) Filter.atTop Filter.atTop := by
        rw [Filter.tendsto_atTop_atTop] at hfk_norm ⊢
        intro M
        obtain ⟨K, hK⟩ := hfk_norm M
        use K
        intro k hk
        have hgK : g k ≥ K := hk.trans (hg_mono.id_le k)
        exact hK (g k) hgK
      -- Key: f (g k) → ∞ because if f (g k) were bounded, then ‖w' (f (g k))‖ would be bounded
      have hf_g_top : Filter.Tendsto (fun k => f (g k)) Filter.atTop Filter.atTop := by
        rw [Filter.tendsto_atTop_atTop]
        intro N
        by_contra h_not_top
        push_neg at h_not_top
        -- h_not_top : ∀ K, ∃ k ≥ K, f (g k) < N
        let M_N := ∑ j ∈ Finset.range N, ‖w' j‖
        have hN_bound : ∀ k, f (g k) < N → ‖w' (f (g k))‖ ≤ M_N := by
          intro k hfk
          apply Finset.single_le_sum (fun j _ => norm_nonneg _)
          simp [Finset.mem_range]
          linarith
        rw [Filter.tendsto_atTop_atTop] at hfk_g_norm
        obtain ⟨K, hK⟩ := hfk_g_norm (M_N + 2)
        obtain ⟨k, hk, hfKN⟩ := h_not_top K
        have h1 : ‖w' (f (g k))‖ > M_N + 1 := by linarith [hK k hk]
        have h2 : ‖w' (f (g k))‖ ≤ M_N := hN_bound k hfKN
        linarith
      -- Now we have hf_g_top : f (g k) → ∞
      -- Continue with the rest of the proof
      have hL_u_g_eq : ∀ k, L (u (g k)) = (1 / ‖w' (f (g k))‖) • seq (f (g k)) := fun k => hL_u_eq (g k)
      -- seq (f (g k)) → hmem (composition of tendsto)
      have hfg_top : Filter.Tendsto (fun k => f (g k)) Filter.atTop Filter.atTop := hf_g_top
      have hseq_fg_lim : Filter.Tendsto (fun k => seq (f (g k))) Filter.atTop (nhds hmem) := 
        hlim.comp hfg_top
      -- L(u (g k)) → 0
      have hL_fg_lim : Filter.Tendsto (fun k => L (u (g k))) Filter.atTop (nhds 0) := by
        simp_rw [hL_u_g_eq]
        have heq : ∀ k, 1 / ‖w' (f (g k))‖ = (‖w' (f (g k))‖ : ℝ)⁻¹ := fun k => by ring
        simp_rw [heq]
        have h1 : Filter.Tendsto (fun k => (‖w' (f (g k))‖ : ℝ)⁻¹) Filter.atTop (nhds 0) := 
          tendsto_inv_atTop_zero.comp hfk_g_norm
        have h2 := h1.smul hseq_fg_lim
        simp at h2
        exact h2
      -- Therefore L(u_lim) = 0
      have hL_u_lim_zero : L u_lim = 0 := tendsto_nhds_unique hL_lim hL_fg_lim
      -- We need S to be nonempty for u_lim to exist (since ‖u_lim‖ = 1)
      haveI hS_nonempty_type : Nonempty S := by
        by_contra h_empty
        have hu_zero : u_lim = 0 := by funext t; exact (h_empty ⟨t⟩).elim
        simp [hu_zero] at hu_lim_norm
      have hS_nonempty : Finset.Nonempty (Finset.univ : Finset S) := Finset.univ_nonempty
      -- Since ‖u_lim‖ = 1, there exists some t with u_lim t > 0
      have h_pos_comp : ∃ t : S, u_lim t > 0 := by
        by_contra h_neg
        push_neg at h_neg
        have h_u_zero : u_lim = 0 := by
          ext t
          exact le_antisymm (h_neg t) (hu_lim_nonneg t)
        simp [h_u_zero] at hu_lim_norm
      -- Let t₀ be such that u_lim t₀ > 0
      obtain ⟨t₀, hut₀_pos⟩ := h_pos_comp
      -- Define α_k = min {w' (f (g k)) t / u_lim t | t ∈ S}
      have hα_def : ∀ k, ∃ t : S, ∀ t' : S, w' (f (g k)) t / u_lim t ≤ w' (f (g k)) t' / u_lim t' := by
        intro k
        obtain ⟨t, _, ht⟩ := Finset.exists_min_image (Finset.univ : Finset S) (fun t => w' (f (g k)) t / u_lim t) hS_nonempty
        exact ⟨t, fun t' => ht t' (Finset.mem_univ t')⟩
      choose t α_eq using hα_def
      let α : ℕ → ℝ := fun k => w' (f (g k)) (t k) / u_lim (t k)
      -- α k ≥ 0 since w' ≥ 0 and u_lim > 0 at t k
      have hα_nonneg : ∀ k, 0 ≤ α k := by
        intro k
        simp only [α]
        exact div_nonneg (hw_nonneg (f (g k)) (t k)) (hu_lim_nonneg (t k))
      -- Define v k = w' (f (g k)) - α k • u_lim
      let v : ℕ → S → ℝ := fun k => w' (f (g k)) - α k • u_lim
      -- v k ≥ 0
      have hv_nonneg : ∀ k t, 0 ≤ v k t := by
        intro k t
        simp only [v, Pi.sub_apply, Pi.smul_apply, smul_eq_mul]
        have h2 : α k ≤ w' (f (g k)) t / u_lim t := α_eq k t
        have h3 : u_lim t ≥ 0 := hu_lim_nonneg t
        by_cases hut_pos : u_lim t > 0
        · have : α k * u_lim t ≤ w' (f (g k)) t := by
            calc α k * u_lim t ≤ (w' (f (g k)) t / u_lim t) * u_lim t := by nlinarith
              _ = w' (f (g k)) t := by field_simp
          linarith
        · have hut_zero : u_lim t = 0 := le_antisymm (not_lt.mp hut_pos) h3
          simp [hut_zero]; exact hw_nonneg (f (g k)) t
      -- The image of the nonnegative orthant under a linear map in finite
      -- dimensions is a finitely generated cone, hence closed (polyhedral).
      -- We use IsSeqCompact on a bounded截面.
      -- Since seq (f (g k)) → hmem and seq n = L (w' n), we have L (w' (f (g k))) → hmem.
      -- The sequence w' (f (g k)) is unbounded, but L (w' (f (g k))) is bounded.
      -- This means the unbounded part is in ker(L).
      -- We construct v k = w' (f (g k)) - α k • u_lim which is bounded.
      -- First find a bound for the "effective" part.
      -- Since L is continuous and L(w' (f (g k))) → hmem, the sequence L(w' (f (g k))) is bounded.
      have hL_seq_tendsto : Filter.Tendsto (fun k => L (w' (f (g k)))) Filter.atTop (nhds hmem) := by
        have h1 : Filter.Tendsto (fun k => seq (f (g k))) Filter.atTop (nhds hmem) := hlim.comp hfg_top
        simp_rw [hw_eq] at h1
        exact h1
      have hL_seq_bdd : ∃ M, ∀ k, ‖L (w' (f (g k)))‖ ≤ M := by
        have := hL_seq_tendsto.norm.bddAbove_range
        rcases this with ⟨M, hM⟩
        exact ⟨M, fun k => hM ⟨k, rfl⟩⟩
      obtain ⟨M, hM⟩ := hL_seq_bdd
      -- Key insight: incidence vectors are nonnegative, and w' ≥ 0, so there's no cancellation.
      -- For each t ∈ S, incidence G t ≠ 0 (since t is a 3-clique, it has edges).
      -- So if ‖L(w' (f (g k)))‖ ≤ M, then each coordinate w' (f (g k)) t is bounded.
      -- This means {w' (f (g k))} is bounded, contradicting ‖w' (f (g k))‖ → ∞.
      --
      -- Let's prove this: for each t, find an edge e with incidence G t e = 1.
      -- Then |L(w' (f (g k))) e| ≥ w' (f (g k)) t.
      have h_inc_pos : ∀ t : S, ∃ e : Sym2 V, incidence G t e = 1 := by
        intro t
        -- t is a 3-clique, so it has at least 2 vertices, hence edges
        have ht_mem : t.val ∈ G.cliqueFinset 3 := t.property
        obtain ⟨ht_clique, ht_card⟩ := G.mem_cliqueFinset_iff.mp ht_mem
        -- Get two distinct vertices in t
        have ht_card_pos : 0 < t.val.card := by linarith
        obtain ⟨v1, hv1, v2, hv2, hne⟩ := Finset.one_lt_card.mp (by linarith : 1 < t.val.card)
        -- The edge {v1, v2} is in t.sym2 and is notdiag
        use Sym2.mk ⟨v1, v2⟩
        simp [incidence, triEdges]
        exact ⟨hv1, hv2, hne⟩
      -- For each t, pick an edge e with incidence G t e = 1
      choose edge hedge using h_inc_pos
      -- The e-coordinate of L(w' (f (g k))) is ≥ w' (f (g k)) t
      -- So w' (f (g k)) t ≤ ‖L(w' (f (g k)))‖ ≤ M
      have hw'_bound : ∀ k t, w' (f (g k)) t ≤ M := by
        intro k t
        have h1 : L (w' (f (g k))) (edge t) = ∑ t' : S, w' (f (g k)) t' • incidence G ↑t' (edge t) := by simp [L]
        have h2 : incidence G ↑t (edge t) = 1 := hedge t
        have h3 : L (w' (f (g k))) (edge t) ≥ w' (f (g k)) t := by
          rw [h1]
          have h_nonneg : ∀ t', 0 ≤ w' (f (g k)) t' • incidence G ↑t' (edge t) := by
            intro t'
            apply mul_nonneg (hw_nonneg (f (g k)) t')
            simp [incidence]
            split_ifs <;> norm_num
          calc w' (f (g k)) t = w' (f (g k)) t • 1 := by simp [smul_eq_mul]
            _ = w' (f (g k)) t • incidence G ↑t (edge t) := by rw [h2]
            _ ≤ ∑ t' : S, w' (f (g k)) t' • incidence G ↑t' (edge t) := by
              apply Finset.single_le_sum (fun t' _ => h_nonneg t')
              exact Finset.mem_univ t
        have h_coord_bdd : L (w' (f (g k))) (edge t) ≤ M := by
          have h1 := hM k
          have h2 : L (w' (f (g k))) (edge t) ≤ ‖L (w' (f (g k))) (edge t)‖ := by
            exact le_abs_self _
          have h3 : ‖L (w' (f (g k))) (edge t)‖ ≤ ‖L (w' (f (g k)))‖ := norm_le_pi_norm _ _
          linarith
        linarith
      -- Now we have a contradiction: all coordinates bounded by M, but norm → ∞
      have h_norm_bdd : ∃ C, ∀ k, ‖w' (f (g k))‖ ≤ C := by
        -- For pi types, ‖v‖ = ⨆ t, ‖v t‖ = ⨆ t, |v t|
        use max M 0
        intro k
        have h1 : ∀ t : S, ‖w' (f (g k)) t‖ ≤ max M 0 := by
          intro t
          have hn : 0 ≤ w' (f (g k)) t := hw_nonneg (f (g k)) t
          have hb : w' (f (g k)) t ≤ M := hw'_bound k t
          rw [Real.norm_eq_abs, abs_of_nonneg hn]
          linarith [le_max_left (α := ℝ) M 0]
        exact pi_norm_le_iff_of_nonneg (le_max_right (α := ℝ) M 0) |>.mpr h1
      obtain ⟨C, hC⟩ := h_norm_bdd
      have := hfk_g_norm.eventually_gt_atTop C
      obtain ⟨k, hk⟩ := this.exists
      exact False.elim (not_le.mpr hk (hC k))
  )
  exact h_closed.mem_of_tendsto hx_lim (Filter.Eventually.of_forall hx_mem')

/-- **S3.** If the all-ones vector is outside the (closed) cone, a Farkas potential separates
it — via `geometric_hahn_banach_closed_point`, representing the separating functional as an
edge potential. The closedness hypothesis `hclosed` comes from S2. -/
theorem farkas_of_target_not_mem (G : SimpleGraph V) [DecidableRel G.Adj]
    (hclosed : IsClosed (triCone G)) (h : targetVec G ∉ triCone G) :
    ∃ y : Sym2 V → ℝ, FarkasPotential G y := by
  let hcone : ConvexCone ℝ (Sym2 V → ℝ) := {
    carrier := triCone G
    add_mem' := by
      intro f hf g hg
      simp only [triCone] at hf hg ⊢
      obtain ⟨wf, hwf, rfl⟩ := hf
      obtain ⟨wg, hwg, rfl⟩ := hg
      use fun t => wf t + wg t
      constructor
      · intro t; exact add_nonneg (hwf t) (hwg t)
      · ext e
        simp only [Pi.add_apply, Finset.sum_apply, Finset.sum_apply, add_smul]
        rw [Finset.sum_add_distrib, Finset.sum_congr rfl]
        intro x _
        ring
    smul_mem' := by
      intro c hc f hf
      simp only [triCone] at hf
      obtain ⟨wf, hwf, hf⟩ := hf
      use fun t => c * wf t
      constructor
      · intro t; exact mul_nonneg (le_of_lt hc) (hwf t)
      · simp only [hf]
        ext e
        simp [Pi.smul_def, mul_assoc, Finset.mul_sum]
  }
  -- The cone is nonempty (contains 0)
  have hnonempty : (triCone G).Nonempty := by
    use 0
    simp only [triCone, Set.mem_setOf_eq]
    use fun _ => 0
    simp
  -- We need to work in a finite-dimensional space
  -- Since V is finite, Sym2 V is finite, hence Sym2 V → ℝ is finite-dimensional
  letI : FiniteDimensional ℝ (Sym2 V → ℝ) := by infer_instance
  have hcarrier : hcone.carrier = triCone G := rfl
  have hconv : Convex ℝ (triCone G) := hcarrier ▸ ConvexCone.convex hcone
  -- Use geometric_hahn_banach_closed_point
  obtain ⟨y, hy⟩ := geometric_hahn_banach_closed_point hconv hclosed h
  -- Use -y instead, so that -y ≥ 0 on cone and -y(targetVec) < 0
  let y_neg : StrongDual ℝ (Sym2 V → ℝ) := -y
  -- Extract the representing vector
  let y' : Sym2 V → ℝ := fun e => y_neg (Pi.single e 1)
  -- We need to show FarkasPotential G y'
  -- Key lemma: y_neg f = ∑ e, y' e * f e for any f
  have hy_eq : ∀ f : Sym2 V → ℝ, y_neg f = ∑ e, y' e * f e := by
    intro f
    -- Express f as sum of basis elements
    have hf : f = ∑ e : Sym2 V, (f e : ℝ) • (Function.update (fun _ => (0 : ℝ)) e 1 : Sym2 V → ℝ) := by
      funext e
      simp [Function.update]
    rw [hf]
    rw [map_sum, Finset.sum_congr rfl]
    intro e _
    rw [map_smul]
    -- Now need: y (Function.update 0 e 1) = y' e
    have h_eq : Function.update (fun _ => (0 : ℝ)) e 1 = Pi.single e 1 := by
      ext x
      simp [Function.update, Pi.single_apply]
    rw [h_eq]
    -- Simplify RHS: (∑ x, f x • Function.update (fun x => 0) x 1) e = f e
    have h_rhs : (∑ x : Sym2 V, f x • Function.update (fun _ => (0 : ℝ)) x 1) e = f e := by
      simp [Function.update, Pi.smul_apply]
    rw [h_rhs]
    simp [y']
    ring
  -- Now prove FarkasPotential G y'
  -- First, from hy for y, derive property for y_neg
  obtain ⟨u, hu_cone, hu_target⟩ := hy
  -- For y_neg: y_neg a = -y a > -u for all a ∈ triCone G
  -- And y_neg (targetVec) = -y (targetVec) < -u
  have hy_neg_cone : ∀ a ∈ triCone G, -u < y_neg a := by
    intro a ha
    simp [y_neg]
    linarith [hu_cone a ha]
  have hy_neg_target : y_neg (targetVec G) < -u := by
    simp [y_neg]
    linarith
  -- Since 0 ∈ triCone G, we have -u < y_neg 0 = 0, so -u < 0
  have h_u_neg : -u < 0 := by
    have h0 : (0 : Sym2 V → ℝ) ∈ triCone G := by
      simp only [triCone, Set.mem_setOf_eq]
      use fun _ => 0
      simp
    simpa using hy_neg_cone 0 h0
  -- For any a in cone, y_neg a ≥ 0 (otherwise scaling contradicts bound)
  have hy_neg_nonneg : ∀ a ∈ triCone G, 0 ≤ y_neg a := by
    intro a ha
    by_contra h_neg
    push_neg at h_neg
    -- Choose c > (-u) / (-y_neg a) so that c * y_neg a < -u
    set c := (-u) / y_neg a + 1 with hc_def
    have hc_pos : 0 < c := by
      simp [hc_def]
      -- (-u) / y_neg a > 0 since -u < 0 and y_neg a < 0
      have : (-u) / y_neg a > 0 := div_pos_of_neg_of_neg h_u_neg h_neg
      linarith
    have hca_mem : c • a ∈ triCone G := hcone.smul_mem' hc_pos ha
    have hca_bound := hy_neg_cone (c • a) hca_mem
    rw [map_smul] at hca_bound
    -- c • y_neg a = c * y_neg a = (-u / y_neg a + 1) * y_neg a = -u + y_neg a < -u
    have hy_ne : y_neg a ≠ 0 := ne_of_lt h_neg
    have hcalc : c • y_neg a = -u + y_neg a := by
      rw [smul_eq_mul, hc_def]
      rw [add_mul, div_mul_cancel₀ _ hy_ne]
      ring
    rw [hcalc] at hca_bound
    linarith
  -- Now prove FarkasPotential G y'
  refine ⟨y', ⟨?_, ?_⟩⟩
  -- 1. Nonnegativity on triangles
  · intro t ht
    -- incidence G t ∈ triCone G
    have hinc_mem : incidence G t ∈ triCone G := by
      simp only [triCone, Set.mem_setOf_eq]
      use fun s => if s = t then 1 else 0
      constructor
      · intro s
        split_ifs <;> norm_num
      · funext e
        simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
        have : ∀ x, (if x = t then (1 : ℝ) else 0) * incidence G x e = if x = t then incidence G t e else 0 := by
          intro x
          by_cases h : x = t <;> simp [h]
        simp_rw [this]
        rw [Finset.sum_ite]
        -- Need to show #{x ∈ G.cliqueFinset 3 | x = t} = 1
        have hcard : #({x ∈ G.cliqueFinset 3 | x = t} : Finset (Finset V)) = 1 := by
          rw [Finset.card_eq_one]
          use t
          ext x
          simp [Finset.mem_filter]
          simp_all
        simp [hcard]
    have htri := hy_neg_nonneg (incidence G t) hinc_mem
    rw [hy_eq] at htri
    -- Show this equals triPotSum y' t
    -- triPotSum y' t = ∑ e ∈ triEdges t, y' e
    -- ∑ e, y' e * incidence G t e = ∑ e, y' e * (if e ∈ triEdges t then 1 else 0)
    unfold incidence at htri
    simp only [triPotSum]
    have heq : ∑ e : Sym2 V, y' e * (if e ∈ triEdges t then (1 : ℝ) else 0) = ∑ e ∈ triEdges t, y' e := by
      simp_rw [mul_ite, mul_one, mul_zero]
      rw [Finset.sum_ite]
      simp
    linarith [htri, heq]
  -- 2. Negative edge sum
  · -- edgePotSum G y' = ∑ e ∈ G.edgeFinset, y' e
    -- We need to show this equals y_neg (targetVec G) < 0
    have h : edgePotSum G y' = y_neg (targetVec G) := by
      rw [hy_eq]
      unfold edgePotSum targetVec
      simp_rw [mul_ite, mul_one, mul_zero]
      rw [Finset.sum_ite, Finset.sum_const_zero, add_zero]
      congr 1
      simp [SimpleGraph.mem_edgeFinset]
      ext x
      simp [SimpleGraph.mem_edgeFinset]
    rw [h]
    linarith

/-- **S4.** No Farkas potential ⇒ fractional decomposition (assembly of S1+S3, using S2). -/
theorem decomp_of_no_farkas (G : SimpleGraph V) [DecidableRel G.Adj]
    (h : ∀ y : Sym2 V → ℝ, ¬ FarkasPotential G y) : FractionalTriangleDecomp G := by
  apply decomp_of_target_mem
  by_contra hmem
  obtain ⟨y, hy⟩ := farkas_of_target_not_mem G (triCone_isClosed G) hmem
  exact h y hy

end Ax2
