/-
# Paper III — clean final assembly gate

This gate checks the final Paper III assembly surfaces with the remaining external inputs kept as
explicit hypotheses. In particular, it does not instantiate the local `AX1` or `AX2` axioms.
-/
import PaperIII.MainNibble

namespace PaperIII

#check @AX1_from_freedmanConcreteBadRound_linearRegularity
#check @AX1_from_freedmanConcreteBadEventRoundIneq_linearRegularity
#check @Theorem_1_1_of_freedmanCardCore_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanCardCore_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanExplicitCardCore_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanExplicitCardCore_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitExplicitCore_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitExplicitCore_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitExplicitNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitExplicitNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitFactoredNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitFactoredNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitCardPenaltyNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitCardPenaltyNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitGainLowerNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitGainLowerNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitProxyScalarNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitProxyScalarNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanSplitProxyIneqNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanSplitProxyIneqNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanBadRoundNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanBadRoundNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanConcreteBadRoundNibble_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanConcreteBadRoundNibble_linearRegularity_AX2
#check @Theorem_1_1_of_freedmanConcreteBadEventRoundIneq_linearRegularity_AX2
#check @Corollary_1_2_of_freedmanConcreteBadEventRoundIneq_linearRegularity_AX2

#print axioms AX1_from_freedmanConcreteBadRound_linearRegularity
#print axioms AX1_from_freedmanConcreteBadEventRoundIneq_linearRegularity
#print axioms Theorem_1_1_of_freedmanCardCore_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanCardCore_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanExplicitCardCore_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanExplicitCardCore_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitExplicitCore_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitExplicitCore_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitExplicitNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitExplicitNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitFactoredNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitFactoredNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitCardPenaltyNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitCardPenaltyNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitGainLowerNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitGainLowerNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitProxyScalarNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitProxyScalarNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanSplitProxyIneqNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanSplitProxyIneqNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanBadRoundNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanBadRoundNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanConcreteBadRoundNibble_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanConcreteBadRoundNibble_linearRegularity_AX2
#print axioms Theorem_1_1_of_freedmanConcreteBadEventRoundIneq_linearRegularity_AX2
#print axioms Corollary_1_2_of_freedmanConcreteBadEventRoundIneq_linearRegularity_AX2

end PaperIII
