"""Auditor report build (fallback, disclosed): tectonic --only-cached failed (no cached format/bundle in
this user profile; downloading resources was not authorized). PDFs are therefore produced by
pandoc (Markdown -> standalone TeX, kept as the TeX source; and Markdown -> HTML) and PyMuPDF Story
(HTML -> PDF). They are NOT compiled from TeX. Page renders are saved for visual inspection."""
import subprocess, pathlib, sys, pymupdf
PANDOC = r'C:/Users/jtraverso/.cache/e81-editorial-tools/pandoc/pandoc-3.11/pandoc.exe'
CSS = """body{font-family:serif;font-size:9.5pt;line-height:1.3} h1{font-size:15pt} h2{font-size:12.5pt} h3{font-size:11pt}
table{border-collapse:collapse;font-size:7pt;width:100%;table-layout:fixed} td,th{border:0.5px solid #888;padding:2px 3px;vertical-align:top}
code{font-family:monospace;font-size:8.5pt} pre{font-size:7.5pt;white-space:pre-wrap}"""
FOOT = "<p style='font-size:7pt;color:#555'>PDF generated by pandoc (HTML) + PyMuPDF Story from the Markdown source; not compiled from TeX. The TeX file alongside is pandoc's standalone conversion of the same Markdown.</p>"
def build(md):
    md = pathlib.Path(md)
    subprocess.run([PANDOC, str(md), '-f', 'gfm', '-s', '-o', str(md.with_suffix('.tex'))], check=True)
    html = subprocess.run([PANDOC, str(md), '-f', 'gfm', '-t', 'html5'], capture_output=True, text=True, encoding='utf-8', check=True).stdout
    import re as _re
    ZW = '​'
    def _brk(m): return m.group(1) + _re.sub(r'([._/-])', lambda k: k.group(1) + ZW, m.group(2)) + m.group(3)
    html = _re.sub(r'(<code>)(.*?)(</code>)', _brk, html, flags=_re.S)
    html = _re.sub(r'(<td[^>]*>)([^<]*)(</td>)', lambda m: m.group(1) + _re.sub(r'([,;/_=])(?=\S)', lambda k: k.group(1) + ZW, m.group(2)) + m.group(3), html)
    story = pymupdf.Story(html=html + FOOT, user_css=CSS)
    pdf = md.with_suffix('.pdf'); w = pymupdf.DocumentWriter(str(pdf))
    rect = pymupdf.paper_rect('a4'); where = rect + (45, 45, -45, -45)
    more = True
    while more:
        dev = w.begin_page(rect); more, _ = story.place(where); story.draw(dev); w.end_page()
    w.close()
    doc = pymupdf.open(pdf); rd = md.parent / 'renders' / md.stem; rd.mkdir(parents=True, exist_ok=True)
    bad = 0
    for i, pg in enumerate(doc):
        if '\ufffd' in pg.get_text(): bad += 1
        pg.get_pixmap(dpi=80).save(rd / f'{i+1:03}.png')
    print(md.name, 'pages', doc.page_count, 'pages_with_replacement_glyph', bad)
for a in sys.argv[1:]: build(a)
