import csv
from pathlib import Path
rows = [
    ("F-01", "MAJOR", "E7", "Thm C (EN l.81-94; abstract l.28; §1 l.46; §8.1 l.1026-1036); ES same",
     "Compare [15] v1 Thm 1.1 (p.2) with Thm C; grep EN/ES for every citation of [15]",
     "20_EVIDENCE/E7/E7_RECORD.md; E7/sources/arxiv_2609.20871v1.pdf; E7/sources/okechukwu_p2.png",
     "Theorem C's eventual maximum Q_s(n) (same class, same Q_s notation, same extremal family) is [15, Theorem 1.1], which also proves cp<=Q_s+K_s at all orders and classifies equality graphs. The manuscript never cites [15, Thm 1.1]; the abstract and Thm C carry no citation of [15]; §8.1 does not state the coincidence. Only the c4 (order<=4) form of the upper bound is specific to Paper IV at statement level. Headline-claim attribution defect.",
     "BLOCKING (release): author to correct attribution; corrected target requires new revision ID and re-audit of E7/E6; E4 not run in this run"),
    ("F-02", "MODERATE", "E2", "(5.4),(5.7) and the degree/width bounds before them; C.2 counts (3.10),(3.8), fibre bounds b_H; C.3 Table C.1; E.1 normalization, (E.2b),(E.2d), three-case budget; D.1 frames",
     "Attempted human rederivation from the prose",
     "20_EVIDENCE/E2/E2_RECORD.md items 4,4c,4d,4e,10a,22,23a",
     "Proof-critical steps presented only as sketches; correctness rests on the Lean development. No defect found, but the manuscript alone does not permit human verification of these steps.",
     "OPEN: expand prose or label explicitly as formally-checked-only; E4 dynamic check still required"),
    ("F-03", "MINOR", "E7", "§1 l.38-40 (antecedents)",
     "erdosproblems proof-claims thread; [5] reference [Cip26]",
     "E7/sources/erdos_forum_thread_81_proof-claims.html; E7/sources/ref5_main.txt l.57",
     "Cipollini's partial result cp<=n^2/6+o(n^2) (claim of 2026-08-10, cited by [5]) is not cited.",
     "Recommend citing as antecedent"),
    ("F-04", "OBSERVATION", "E7", "Thm A l.60; §1 l.48", "erdosproblems.com/81 retrieved 2026-09-28",
     "E7/sources/erdosproblems_81.html",
     "Site lists #81 as OPEN with 4 unreviewed proof claims; 'answers Erdős Problem 81' is the author's mathematical claim; [8] already disclaims status certification.",
     "No action required"),
    ("F-05", "OBSERVATION", "E7", "§8.1 l.1040", "[15] §7 p.23", "E7/sources/okechukwu_v1.txt l.1479-1486",
     "[15] explicitly asks for a quantitative version of its Cor 5.5; Thm 6.1 supplies one for s=0 (linear rate 16δ, hypothesis on c4, which is weaker than one on cp).",
     "Optional mention"),
    ("F-06", "MINOR", "E6", "EN PDF p.27 and passim; ES PDF passim", "Visual inspection and extracted text",
     "20_EVIDENCE/E6/pdftext_en.txt, pdftext_es.txt, pages/",
     "Lean identifiers set in roman and broken across lines without marker (e.g. PASS_INTERNAL_AU|THOR_SIDE; ES NearH1CalibratedRo|ot).",
     "Typography"),
    ("F-07", "MINOR", "E6", "EN md l.1745", "Numeric-token diff EN vs ES md", "20_EVIDENCE/E6/e6_auto.json",
     r"Stray LaTeX directive \Needspace{20\baselineskip} in the EN Markdown only.", "Editorial"),
    ("F-08", "OBSERVATION", "E0", "01_manuscript/v1.0.1_candidate/*.aux", "Candidate directory vs MANIFEST.json",
     "20_EVIDENCE/E0/E0_intake_summary.json", "Two .aux files present but not listed in MANIFEST.json.", "Housekeeping"),
    ("F-09", "OBSERVATION", "E3", "Prop 6.3 (6.10); SplitMixedGap.mixed_gap_zero", "Static header reading",
     "20_EVIDENCE/E3/headers_part2.txt",
     "Lean gives the fractional upper bound and a clique partition of gain 2C(k,2); W(S)=W*(S) for mixed packings follows only in combination with SplitCompleteSharpValue.",
     "Wording only"),
    ("F-10", "OBSERVATION", "E3", "Thm 6.1; Cor 6.1a", "Static header reading", "20_EVIDENCE/E3/headers_part1.txt",
     "Lean: δ rational (harmless), γ = η0/4 explicit; Cor 6.1a quantifies τ over all rationals (stronger than τ>=0); the root precedes every Q (matches the manuscript).",
     "None"),
    ("F-11", "OBSERVATION", "E2/E5", "Thm 6.1 (16), Cor 6.1a (48)", "LP over the retained account (6.7)",
     "20_EVIDENCE/E5/e5_exact_results.json",
     "16 and 48 are exactly the best constants derivable from account (6.7) (negative control 47 fails); using the (5.15a) coefficients directly would allow about 46.8.",
     "None"),
    ("F-12", "OBSERVATION", "E7", "§7 l.921", "[5] repository tree at cbde8a0a", "E7/sources/ref5_tree.txt",
     "FORMALIZATION_STATUS.md lives at lean/FORMALIZATION_STATUS.md; its content matches the manuscript's description.",
     "Optional path precision"),
    ("F-13", "INFO", "ALL", "Independence", "Manuscript l.1753; auditor identity", "00_CONTROL/AUDITOR_DECLARATION.md",
     "Auditor (Claude Opus 5.5) belongs to the model family used to check arguments and prepare the manuscript; same machine and dependency cache.",
     "Recorded limitation"),
    ("F-14", "CORRECTION", "auditor", "00_CONTROL timestamps; E6 font list", "Self-check vs system clock and subset font prefixes",
     "00_CONTROL/AUDITOR_DECLARATION.md; 20_EVIDENCE/E6/E6_RECORD.md",
     "Auditor hand-entered a wrong time (11:40 instead of about 11:05) and produced a false-positive 'non-embedded fonts' list; both corrected, originals described.",
     "Corrected"),
]
out = Path(__file__).resolve().parent / 'FINDINGS.csv'
with open(out, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['id', 'severity', 'gate', 'location_or_claim', 'reproduction', 'evidence', 'impact', 'disposition'])
    w.writerows(rows)
print(len(rows), 'rows ->', out)
